stages:
  - lint

markdown-lint:
  stage: lint
  image: davidanson/markdownlint-cli2
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - markdownlint-cli2 "**/*.md"
